### ISSUE TITLE
Cloudflare protection redirect loop

### ISSUE THREAD

**Issue by Squall-Leonhart** [MrAlex94/Waterfox-Old#107]
**Describe the bug**
Browser check never succeeds.

**To Reproduce**
1. Go to 'steamdb.info'

**Expected behavior**
Brower check completes

**Screenshots**
![image](https://user-images.githubusercontent.com/1098176/166652913-b58f1a1f-0cc8-4cb4-85b2-be28943d90a9.png)
![image](https://user-images.githubusercontent.com/1098176/166652861-b979d6cc-a54b-4402-8fcb-5860fb16fa27.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 7/10

**Comment by condoghost** [comment]
Having same problem with another website using cloudflare protection

**Comment by reallyuniquename** [comment]
Related: https://forum.palemoon.org/viewtopic.php?f=70&t=28227

**Comment by buttercookie42** [comment]
It seems like it's working again normally with the regular Waterfox user agent.

Curiously enough, it's also working if you spoof a Firefox 91 user agent, and when I tried mozregression to test old Firefox Nightlies, I got this regression range somewhere in the middle of Firefox 70, whatever that means exactly: https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=404680ad41e4e7d08aa46081a70095486f14e15f&tochange=e704e3565db9260efaa854f2916ca023b717db3c

**Comment by reallyuniquename** [comment]
-deleted-

**Comment by buttercookie42** [comment]
Additional note: The above is definitively true for steamdb.info, but the other two pages mentioned in the Palemoon thread (and others using similar paranoid Cloudflare settings?) might still be problematic. The regression range for a real Firefox still holds (i.e. things start working normally starting from Firefox 70-ish), but Waterfox still gives problems.

While I do remember seeing that Cloudflare redirect from time to time, unfortunately I cannot remember on which pages exactly, so can't experiment with other pages right now.

**Comment by decembre** [comment]
Same for me, by example if i open a CodePen (these one with a button "Open in CodePen")  in another Tab from:
<a href="https://stackoverflow.com/questions/38145368/css-workaround-to-backdrop-filter">[CSS: Workaround to backdrop-filter?](https://stackoverflow.com/questions/38145368/css-workaround-to-backdrop-filter)</a>

I tested User agent:
Windows / Firefox 83
Seems working, but not always....

Sometime, i show the Captcha, resolve it:
Cloudflare verification and it open the code pen but it is not functional:
It seems the good page, but the url in the address Bar don't be related to the desired CodePen but the general one (https://codepen.io). 

Maybe too a Cloudflare problem.
Some info here:
<a href="https://community.cloudflare.com/t/browser-integrity-check-broken/381029">[Browser Integrity Check broken](https://community.cloudflare.com/t/browser-integrity-check-broken/381029)</a>

Found it in previous posted link:
<a href="https://forum.palemoon.org/viewtopic.php?f=70&amp;t=28227">Cloudflare &quot;Checking your browser&quot; infinite redirect on multiple sites</a>

**Comment by reallyuniquename** [comment]
Changing useragent doesn't work for some sites. Although I can actually see JS error in the logs.
```
TypeError: window[(b(...) + b(...))] is undefined
```
And it's in that obfuscated script.

**Comment by Marsillio** [comment]
Same problem here!
I'm unable to open any site that uses Cloudflare browser check!, Endless loop!!

**Comment by cicku** [comment]
This issue should be fixed now.

**Comment by Squall-Leonhart** [comment]
Yep, confirmed.

Guess it was there end after all, despite their unpaid PR guy telling us it was the browsers fault.

**Comment by cicku** [comment]
Which PR? Please let me know.

**Comment by Squall-Leonhart** [comment]
the responder here https://community.cloudflare.com/t/browser-integrity-check-broken/381029/3

**Comment by cicku** [comment]
Oh yes definitely unpaid…lol

**Comment by decembre** [comment]
Always have problem with the looping check...
No solution for Waterfox Classic ?
