### ISSUE TITLE
CSS ::backdrop  support for WaterFox Classic ? (avaible for Firefow > 47)

### ISSUE THREAD

**Issue by decembre** [MrAlex94/Waterfox-Old#109]
I see in CSS Tricks,  it is available since version 47:
<a href="https://css-tricks.com/almanac/selectors/b/backdrop/">[::backdrop](https://css-tricks.com/almanac/selectors/b/backdrop/) [CSS Tricks]</a>
If Waterfox Classic is based on version 57, why it is not supported?

Note:
In about:config i don't see nothing related to it...

**Comment by lokpro** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/::backdrop#examples
It only works on fullscreen elements.

And, based on version  ~57~ 56

**Comment by decembre** [comment]
Haaa yes!
Sorry, i have not read carefully the explanation.
And thanks for the precision on the based version too.

Hmmm .... I need a coffee....
