### ISSUE TITLE
Save to bookmarks doesn't works

### ISSUE THREAD

**Issue by vitokorn** [MrAlex94/Waterfox-Old#115]
Bookmark this page doesn't work in 2022.04 (64 bit)

Steps to reproduce:
1. Click on star near url string or click Ctrl+D
2. Then open bookmarks, and recent bookmark is not recent

**Expected behavior**
Save to bookmarks works

**Screenshots**
![Animation](https://user-images.githubusercontent.com/68494870/168444814-880ac24b-872e-4b60-adf1-280852914d46.gif)

 - OS: Windows 10 Enterprise LTSB 2016

**Comment by Squall-Leonhart** [comment]
Bookmark this page does work, the inability to add bookmarks is usually a result of the places.sqlite corrupting.

You can delete this file and the bookmarks will be restored from a backup, at the expense of previous browsing history.

There is also a way to repair the file using sqlite3.exe

https://superuser.com/questions/111998/how-do-i-repair-a-corrupted-firefox-places-sqlite-database

**Comment by vitokorn** [comment]
Thanks, this works
