### ISSUE TITLE
Classic crash on Jitsi if sound allowed

### ISSUE THREAD

**Issue by timur-g** [MrAlex94/Waterfox-Old#120]
Classic 2022.04 (I had that also before) crashes in Windows 7 on Jitsi web pages, if microphone is allowed. 
My microphone is shown as "Realtek High Definition Audio". Also with empty profile. 
Can be easily tested with Jitsi Meet that doesn't ask for registration: https://meet.jit.si/

**Comment by Killogy** [comment]
Doesn´t crashed for me. I clicked on Settings icon on top right, clicked on Devices and then allowed permissions and a Mic icon is showed on top of the Browser window.

**Comment by timur-g** [comment]
Crashes either way, on joining the session or via Settings/Devices.
Mic and Jitsi work, so it's not some general driver problem.

**Comment by Squall-Leonhart** [comment]
update your realtek driver.

**Comment by timur-g** [comment]
Updating was a pain as it's a large file very slow from Realtek. But seems like no crash. Thanks.
