### ISSUE TITLE
Problem with gettr and dates of the builds

### ISSUE THREAD

**Issue by Felipefpl** [MrAlex94/Waterfox-Old#132]
The site https://gettr.com/ doesnt open in waterfox classic and the dates on june builds recently released have the month 04 attached to them.

**Comment by adamp01** [comment]
Thanks for the note on build naming being incorrect, resolved that one.

As for the error with gettr, I believe this will be fixed by changes @buttercookie42 (seems to be related to `import`) is introducing.

**Comment by buttercookie42** [comment]
No idea how flawlessly it'll work, but I can confirm that that page does load successfully in my local build.

**Comment by Felipefpl** [comment]
@adamp01 - you're welcome, thanks for the info about buttercookie42.

@buttercookie42 - i tried with latest build and it didnt work, unless it's something you changed on your side.

**Comment by buttercookie42** [comment]
Well yes, which is why I said my *local* build. You can try [this one](https://github.com/buttercookie42/Waterfox-Classic/actions/runs/2556805234), though, once it finished building that is. It's based on https://github.com/buttercookie42/Waterfox-Classic/commits/exportstar and does include the changes for supporting dynamic module import.

**Comment by Felipefpl** [comment]
Strange, it didnt work here, it displayed a blank page like the normal builds.

**Comment by quroe** [comment]
> Strange, it didnt work here, it displayed a blank page like the normal builds.

Did you try clean profile?
I test buttercookie42's Windows build, the page displayed fine.

**Comment by Felipefpl** [comment]
@quroe - Thank you for the tip, i deleted waterfox, temp/log files and the folders in the users' folder and it worked. I didnt do that before.

Thanks again @buttercookie42 for fixing this. I only noticing a small problem with the X button in the tabs, it's too big and it partially disappears when clicking on it to close the tabs.
