### ISSUE TITLE
Can't play videos on Vimeo

### ISSUE THREAD

**Issue by dvc50** [MrAlex94/Waterfox-Old#134]
Vimeo.com has changed something in the last few days. I can no longer play videos using the Classic browser. I tried both 2022.04 and 2022.06. I get blank areas between the header and footer on each page where the video and content should be. 
Example: [](url)https://vimeo.com/236386842

![Vimeo_-_no_video_2022-06-25](https://user-images.githubusercontent.com/108163858/175757285-20fedf27-965d-4704-a060-b411263641e4.jpg)

If I set the browser User-Agent to Android Phone/Firefox 83, I can play videos again, but the page looks designed for Android.

**Comment by quroe** [comment]
You need switch `dom.webcomponents.enabled` to `true`.

**Comment by Sa-Ja-Di** [comment]
@quroe and @dvc50 - Actually no need for this, you just need to make an 

about:config 

override - that works in Pale Moon for me without activating incomplete Webcomponent support and should work in Waterfox Classic too:

------------------------------------------------------------------
------------------------------------------------------------------

About:config string name (Right-click - new - String) =
------------------------------------------------------------------
general.useragent.override.vimeo.com


About:config value =
------------------------------------------------------------------
Mozilla/5.0 (iPhone; CPU iPhone OS 15_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) EdgiOS/102.0.1245.30 Version/15.0 Mobile/15E148 Safari/604.1

------------------------------------------------------------------
------------------------------------------------------------------

Btw. that user agent helps also to get the mobile page variant of Youtube which makes it more lighter and delivers towards Facebook users the less demanding mobile Facebook variant too.

Btw. if you do not feel comfortable with adding a Safari user-agent override, something like that works too, offers the same result which does also not require activating web components:

Mozilla/5.0 (iPhone; CPU iPhone OS 15_5 like Mac OS X; rv:5.1) Goanna/20220506 PaleMoon/31.0.0
