### ISSUE TITLE
Pics are not displayed on nintendo of america

### ISSUE THREAD

**Issue by Felipefpl** [MrAlex94/Waterfox-Old#139]
The pics arent displayed in the site and even when click in the pics to maximize them they still arent displayed. Using waterfox 06-2022

https://www.nintendo.com/store/products/sega-ages-phantasy-star-switch/

**Comment by WaywardHeart** [comment]
After playing around with the CSS in chrome, it seems the site is preferentially using the aspect-ratio attribute, and the site's fallback code doesn't work in chrome, either.

Here's the tracking bug for aspect-ratio should anyone want to backport it: https://bugzilla.mozilla.org/show_bug.cgi?id=1528375

**Comment by Squall-Leonhart** [comment]
this is resolved on nintendos end.

**Comment by Felipefpl** [comment]
Indeed, thanks @Squall-Leonhart for telling us.
