### ISSUE TITLE
Mac OS 13 (Ventura)

### ISSUE THREAD

**Issue by wd3mo** [MrAlex94/Waterfox-Old#165]
**Describe the bug**
After the update to Mac OS 13 Ventura Waterfox Classic is showing a completely transparent window. The menu bar is displayed and seems to work (file, history, etc.).

**To Reproduce**
1. Update to Mac OS 13
2. open Waterfox
3. see transparent window

**Expected behavior**
see the application

**Screenshots**
<img width="1003" alt="image" src="https://user-images.githubusercontent.com/46442291/197640565-d768c8f1-553b-46ca-9367-5b5919af63af.png">

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Version 13

**Comment by schloerg** [comment]
the same here. Needs to be updated. This happened before with other Mac OS updates. I need Waterfox classic!

**Comment by veo** [comment]
same

**Comment by wd3mo** [comment]
Here is a related PR. This might take a little while. If you want to use XUL, the White Star Browser may be an alternative for now as it will hopefully get an update today.

https://github.com/WaterfoxCo/Waterfox-Classic/pull/162

**Comment by dbsoft** [comment]
I have a partial fix for it... the fix I used in White Star works on any main windows, but popup windows (like menus, autocomplete and downloads) are still blank.  Working on figuring it out right now.

**Comment by dbsoft** [comment]
Echoing what I posted in the pull request, can people test this fix and see if it works without causing other issues?

If you can't compile your own and want to test, you can download the build I am using here: https://dbsoft.org/whitestar/waterfox-classic-2022.08.en-US.mac.dmg

This build should fix transparent windows on Ventura and report the correct MacOS version.

**Comment by schloerg** [comment]
Hey dbsoft
thank you, working for me, like a charm...

**Comment by wd3mo** [comment]
@dbsoft Thanks a lot for that fix! I can confirm that it works perfectly!

**Comment by dbsoft** [comment]
@schloerg @wd3mo Thanks for testing! Hope it works for you all... I have another couple things reported on the other issue, but not Ventura specific (they affect Monterey and Big Sur I think) so not sure if you want to close this issue or not.  The change has already been merged.

**Comment by schloerg** [comment]
@dbsoft, this is all I wanted and it is solved for me, thank's a lot, again.

**Comment by arimuras** [comment]
Mouseover
YouTube FullScreen

**Comment by dbsoft** [comment]
@wd3mo The new build is out with Ventura support... can this issue be closed?

**Comment by arimuras** [comment]
Movie FullScreen Repeat

**Comment by kurukurupippi** [comment]
sorry for translation english
Repeating full screen video playback results in blank display with audio only

**Comment by dbsoft** [comment]
> sorry for translation english Repeating full screen video playback results in blank display with audio only

Figured this was the same fullscreen problem I just fixed... I successfully watched a youtube video, switched to fullscreen and it worked fine.... I did notice a problem however switching back from fullscreen... it started drawing the titlebar text on top of the tabs at the top.  So something isn't quite right but I did not get a blank screen.

**Comment by LeeBinder** [comment]
@dbsoft Brian, would it be possible for you to also apply these fixes to legacy Thunderbird? It also stopped working in Ventura showing a completely transparent window.

The source code of the latest version supporting XUL Extensions is here:

https://archive.mozilla.org/pub/thunderbird/releases/52.9.1/source/

If you require, I would create a new repository in my GitHub account and upload it.

Would be great if you could let me know.

(oh, and also lots of kudos for White Star 👍  !!)

> Echoing what I posted in the pull request, can people test this fix and see if it works without causing other issues?
> 
> If you can't compile your own and want to test, you can download the build I am using here: https://dbsoft.org/whitestar/waterfox-classic-2022.08.en-US.mac.dmg
> 
> This build should fix transparent windows on Ventura and report the correct MacOS version.

**Comment by dbsoft** [comment]
> Brian, would it be possible for you to also apply these fixes to legacy Thunderbird? It also stopped working in Ventura showing a completely transparent window.

Would a build of Epyrus work?  It is based on Thunderbird but using UXP (what White Star is based on) instead?

http://www.epyrus.org/
https://forum.palemoon.org/viewforum.php?f=73

**Comment by LeeBinder** [comment]
@dbsoft very interesting, thanks for the links. Sounds promising, but unfortunately there is no macOS port:

http://www.epyrus.org/download.html

I wasn't even able to find an unofficial compile.

Have you succeeded in compiling Epyrus for macOS Ventura?
______________

[athenian200 ](https://repo.palemoon.org/athenian200)commented [2 weeks ago](https://repo.palemoon.org/athenian200/epyrus/issues/51#issuecomment-32834):
> As for Mac... well, that's ultimately up to whoever winds up dealing with the Mac version, neither of us have a way of dealing with Mac.

**Comment by dbsoft** [comment]
I was offering to make a build if that would work for you.

**Comment by LeeBinder** [comment]
That would be truly fabulous, @dbsoft - I very much appreciate your kind offer. Epyrus seems to be a well-maintained continuation of legacy TB.

As not to hijack this issue thread any further, I opened a new topic over at the [Epyrus forum](https://forum.palemoon.org/viewforum.php?f=73). Because it's my first post over there, it needs to be approved by a board admin.

I'll post the link to the post once it's life.

**Comment by LeeBinder** [comment]
@dbsoft still waiting for topic approval by [athenian200](https://forum.palemoon.org/memberlist.php?mode=viewprofile&u=17830).

Would forum.palemoon.org/epyrus actually be the best or at least a comfortable place for your to continue this venture, or would you prefer a different spot on the web? I don't see a forum section on https://dbsoft.org/, but maybe you'll decide to fork Epyrus into a new repository at https://github.com/dbsoft? Whatever suits you best.

**Comment by dbsoft** [comment]
https://dbsoft.org/forum/ is my forum but happy to continue on pale moon site... I'd prefer not to fork if possible... I'll talk to athenian after the holiday.

**Comment by LeeBinder** [comment]
neat, I wasn't aware you already have a forum at dbsoft. OK, we'll see if athenian is fine with continuing over on the pale moon forum. Otherwise there would be the option to open an Epyrus (MacPyrus?) section on dbsoft.org/forum, I guess.

Enjoy the holiday.

[UPDATE] great, found your new [Mac builds](https://forum.palemoon.org/viewtopic.php?f=73&t=29114) topic over at forum.palemoon.org so this topic can be put to rest here now.

([athenian200](https://forum.palemoon.org/memberlist.php?mode=viewprofile&u=17830) hasn't visited the board since 11/22 so my topic (1st one) still hasn't been approved, but that shouldn't matter anymore now).

**Comment by kurukurupippi** [comment]
Metal 3

**Comment by kurukurupippi** [comment]
Metal 3
