### ISSUE TITLE
Sync no longer working properly

### ISSUE THREAD

**Issue by IsletsOfLangerhans** [MrAlex94/Waterfox-Old#167]
Having issues with Firefox sync in Waterfox Classic (2022.08)  I able to sign into my Firefox account, and the service shows as connected, and is visible when viewing accounts.firefox.com from other Firefox and Waterfox instances.  

However, data is not syncing, and Waterfox Classic shows me as not logged into sync under Tools and Synced Tabs ("Sign In To Sync").

**Comment by michael-j-oconnor** [comment]
I use Firefox Sync for pushing individual URLs between browser instances (mostly between desktop and phone) and that seems to be working to/from Waterfox Classic 2022.08.  It might well be the Sync service itself, which can be flaky.

**Comment by IsletsOfLangerhans** [comment]
I don't think it's an issue with the Sync service, because Classic itself doesn't show that I am logged in.

**Comment by IsletsOfLangerhans** [comment]
Okay, seems to have been an add-on issue; was able to resolve by logging into Sync while in Safe Mode.
