### ISSUE TITLE
Upgraded to 2021.10 and the whatsnew page is not found

### ISSUE THREAD

**Issue by Robbbert** [MrAlex94/Waterfox-Old#17]
It goes to https://www.waterfox.net/blog/waterfox-2021.10-release/ , but it says

Page Not Found

We could not find what you were looking for.

Please contact the owner of the site that linked you to the original URL and let them know their link is broken.

**Comment by Robbbert** [comment]
Fixed in 2021-11.
Thanks.

**Comment by SkyCharger001** [comment]
broken again, 2022-02 to 2022-04

**Comment by lokpro** [comment]
It is normal, links to https://github.com/WaterfoxCo/Waterfox-Classic/releases/tag/2022.02-classic and https://github.com/WaterfoxCo/Waterfox-Classic/releases/tag/2022.04-classic

**Comment by SkyCharger001** [comment]
not through the new-update-available pop-up

**Comment by lokpro** [comment]
yes , you are right.
broken link in here:
![image](https://user-images.githubusercontent.com/2010297/164158719-36d5c21c-d24e-4e7a-ac80-cd7d102226eb.png)
