### ISSUE TITLE
No Windows version 2022-11

### ISSUE THREAD

**Issue by ecsjjgg** [MrAlex94/Waterfox-Old#176]
Why haven't you compiled a windows version of 2022-11?

**Comment by LeeBinder** [comment]
https://github.com/WaterfoxCo/Waterfox-Classic/issues/173

**Comment by ljcool2006** [comment]
In the meantime you could use the testing version: https://github.com/WaterfoxCo/Waterfox-Classic/suites/9390823512/artifacts/442956265

**Comment by ljcool2006** [comment]
This is now fixed.
