### ISSUE TITLE
Waterfox Classic not detecting the newest update

### ISSUE THREAD

**Issue by ljcool2006** [MrAlex94/Waterfox-Old#180]
**Describe the bug**
Waterfox Classic is not detecting the newest update.

**To Reproduce**
1. Click on "About Waterfox"
2. Wait for it to check updates
3. See "Waterfox is up to date"

**Expected behavior**
Waterfox would detect the update and download it

**Screenshots**
![image](https://user-images.githubusercontent.com/51834343/203612924-50d96758-f01e-4307-9e09-fd61f3db3888.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 2022.08

**Additional context**
I think it's because the aus-upload-release action is still waiting for review and someone has cancelled it without being aware that the action needs review.

**Comment by ljcool2006** [comment]
@adamp01 @MrAlex94 Could you [approve the action](https://github.com/WaterfoxCo/Waterfox-Classic/actions/runs/3531047194) so that I could see if it fixes the issue?

**Comment by adamp01** [comment]
Thanks @ljcool2006 - we had to resolve quite a few build issues that had arisen since the last release, and they were only fully resolved as of yesterday. We always do a "soft release" for a day or two before fully pushing out the update.

We will complete the release today.
