### ISSUE TITLE
cdromance doesnt load

### ISSUE THREAD

**Issue by Felipefpl** [MrAlex94/Waterfox-Old#190]
The site uses cloudfare to protect itself and keeps loading and loading:

https://cdromance.com/

**Comment by robbely** [comment]
I'm finding the same with cloudflare generally at the moment

**Comment by psonnosp** [comment]
Still the same and it makes using Waterfox near impossible.
Is this the end of the road?

**Comment by Felipefpl** [comment]
> Still the same and it makes using Waterfox near impossible. Is this the end of the road?

Honestly, i hope they kill waterfox classic if they dont care to update it. It's better than keep it in the limbo forever.

**Comment by cn2t** [comment]
Several of my frequently used websites cannot be accessed because of this problem.

**Comment by robbely** [comment]
No changes to waterfox, but cloudflare seems to be working again now - possibly fixed cloudflare's end

**Comment by Felipefpl** [comment]
@robbely - Thanks for telling me this :+1: - i'll close this issue.
