### ISSUE TITLE
Imgur doesn't work

### ISSUE THREAD

**Issue by Felipefpl** [MrAlex94/Waterfox-Old#40]
Imgur doesnt work at all with the 2021-11 release, didnt try other ones though. The link below can give you an example:

https://imgur.com/a/sKMLjIV

The site works fine on firefox.

**Comment by hawkeye116477** [comment]
Just leave beta version, see https://forum.palemoon.org/viewtopic.php?f=70&t=27334&p=220224&hilit=imgur#p220224 for solution.

**Comment by Purfview** [comment]
https://imgur.com/beta/disable

**Comment by Felipefpl** [comment]
Tried both and it worked, thanks to you 2 for your help.
