### ISSUE TITLE
SteamDB crashes Waterfox

### ISSUE THREAD

**Issue by reaper666735** [MrAlex94/Waterfox-Old#51]
**Describe the bug**

https://steamdb.info/  crashes WF when it tries to do a security redirect (something like cloudflare), not sure if it's JS related

**To Reproduce**

1. Go to ' https://steamdb.info/ '
2. See error ' WF has crashed '

 - Version 2021.11 (64bit)

**Comment by Killogy** [comment]
@reaper666735  Did not crashed for me.

**Comment by hawkeye116477** [comment]
I can't reproduce that too.

**Comment by reaper666735** [comment]
is there anyway for me to try and log this error ?, can't seem to find waterfox logger ....
