### ISSUE TITLE
Cannot sign in firefox account in waterfox classic 2021.11

### ISSUE THREAD

**Issue by ghost** [MrAlex94/Waterfox-Old#54]
**Describe the bug**
Cannot sign in firefox account in waterfox classic 2021.11,it says Blocked by Content Security Policy.

**To Reproduce**
1. Go to 'Setting'
2. Click on 'Sync'
3. Scroll down to 'Sign In'

**Expected behavior**
Open the login in page.

**Screenshots**
![图片](https://user-images.githubusercontent.com/32984303/149519674-b95ab04d-6e15-440d-b653-f66ede9aef0c.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]Windows 7
 - Version [e.g. 22]6.1.7601

**Additional context**

**Comment by Killogy** [comment]
@Rosabis you can sign in by visiting https://accounts.firefox.com/?context=fx_desktop_v3&entrypoint=preferences&action=email&service=sync

**Comment by ghost** [comment]
> @Rosabis you can sign in by visiting https://accounts.firefox.com/?context=fx_desktop_v3&entrypoint=preferences&action=email&service=sync

Yeah,it works.

**Comment by hawkeye116477** [comment]
It's still not solved in app, so shouldn't be rather closed.

**Comment by Killogy** [comment]
This problem has been solved on latest Waterfox 2022.04 version, so this topic can be closed now.
