### ISSUE TITLE
Waterfox archive 2022.02 corrupted?

### ISSUE THREAD

**Issue by mwat56** [MrAlex94/Waterfox-Old#73]
**Describe the bug**

I tried to unpack waterfox-classic-2022.02.en-US.linux-x86_64.tar.bz2 but got errors.

**To Reproduce**

1. download the archive
2. run `tar -xvf <archivename>`
3. Watch the screen
4. See:
```
    [… many more files extracted …]
    waterfox-classic/libfreeblpriv3.chk
    waterfox-classic/waterfox-bin

    bzip2: Data integrity error when decompressing.
            Input file = (stdin), output file = (stdout)
    
    It is possible that the compressed file(s) have become corrupted.
    You can use the -tvv option to test integrity of such files.

    You can use the `bzip2recover' program to attempt to recover
    data from undamaged sections of corrupted files.

    tar: Unexpected EOF in archive
    tar: Unexpected EOF in archive
    tar: Error is not recoverable: exiting now
```
Running `tar -tvvf <archivename>` produces the same error.

**Expected behavior**

Extraction of the archive's contents without errors.

**Desktop (please complete the following information):**

 - OS: GNU/Linux
 - Version "Ubuntu 18.04.6 LTS"

**Additional context**

Any ideas, please?

**Comment by mwat56** [comment]
I downloaded the archive again:
```
matthias@Nele:~/Downloads$ stat waterfox-classic-2022.02.en-US.linux-x86_64.tar.bz2~ ;stat waterfox-classic-2022.02.en-US.linux-x86_64.tar.bz2 
  File: waterfox-classic-2022.02.en-US.linux-x86_64.tar.bz2~
  Size: 96171971        Blocks: 187848     IO Block: 4096   regular file
Device: 821h/2081d      Inode: 42347049    Links: 1
Access: (0664/-rw-rw-r--)  Uid: ( 1000/matthias)   Gid: ( 1000/matthias)
Access: 2022-02-28 21:08:39.239780174 +0100
Modify: 2022-02-28 21:08:39.699774923 +0100
Change: 2022-02-28 22:09:36.903646094 +0100
 Birth: -
  File: waterfox-classic-2022.02.en-US.linux-x86_64.tar.bz2
  Size: 96171971        Blocks: 187848     IO Block: 4096   regular file
Device: 821h/2081d      Inode: 42347050    Links: 1
Access: (0664/-rw-rw-r--)  Uid: ( 1000/matthias)   Gid: ( 1000/matthias)
Access: 2022-02-28 22:10:56.002901818 +0100
Modify: 2022-02-28 22:10:56.494897133 +0100
Change: 2022-02-28 22:10:56.510896981 +0100
 Birth: -
```

So both files seem identical.
However …
Trying to extract the files from the archive this time works without any errors!

Now I did a recursive `diff` between the both directories (from the broken archive and the new one. That produced a `diff` file of about 21KB with ~600 lines (which for one reason or another I can't attach, neither as `.diff` nor as `.txt` or `.gz`: "Something went really wrong, and we can't process that file.").

Anyway, my personal problem seems to be fixed, but the question, why I got a corrupted archive in the first place, still remains mysterious …

**Comment by mwat56** [comment]
Hmm, after several unsuccessful attempts I checked my JavaScript/NoScript settings and allowed `objects-origin.githubusercontent.com` and what happens?

The [waterfox-classic-2022.02.en-US.diff.gz](https://github.com/WaterfoxCo/Waterfox-Classic/files/8157114/waterfox-classic-2022.02.en-US.diff.gz) upload suddenly worked!

Don't you just hate it when some JS-coders reinvent functionality that's been part of HTML for ages (like file upload)?

Anyway, the `.diff` file shows the differences between the corrupted and the working WaterFox archive.

**Comment by hawkeye116477** [comment]
There is [checksum file](https://github.com/WaterfoxCo/Waterfox-Classic/releases/download/2022.02-classic/waterfox-classic-2022.02.sha256) available, so you can use it to verify if download was successful.

**Comment by timur-g** [comment]
Please close this.
