### ISSUE TITLE
Can't log in to LinkedIn with Waterfox 2022.02 (64-bit)

### ISSUE THREAD

**Issue by hlloyge** [MrAlex94/Waterfox-Old#78]
Since I updated to 2022.02, it hangs indefinitely when signing in to www.linkedin.com.
That is: I can enter the username/pass, but when it should show my profile's home page, it hangs.

In previous versions Waterfox worked *very* slow with LinkedIn (half a minute or more to refresh the page), but now it stops completely.

I tried disabling extensions (Adblock Plus and Privacy Badger - these are the only ones I use), but it's the same.

Best regards.

**Comment by rebop** [comment]
Same here. A big bummer.

Please post if you find a solution. I have tried all the tricks in my bag - safe mode, User Agent, clear cookies and cache....

**Comment by michael-j-oconnor** [comment]
It's not 2022.02, but some change on the LinkedIn side, where Waterfox doesn't like what's being sent pretty early after you successfully authenticate.  Others are seeing this, too:

https://www.reddit.com/r/waterfox/comments/tb1bkr/another_broken_site_in_classic_linkedin/

**Comment by jmblazquezh** [comment]
Same problem. I can't access to LinkedIn website. Page all the time loading, but in blank...

**Comment by rebop** [comment]
I wrote LinkedIN. The short story, they do not care about Waterfox and have not looked to see if it is a simple line of code to change. I told them how unsatisfactory their customer service reply was.

**Comment by hlloyge** [comment]
@rebop: Unsatisfactory indeed, but to be expected...

If other browsers work (Firefox does - I tried) it's up to Waterfox to follow their lead, unless it's really contrary to some fundamental specification (say security). Unfair, I know. Alas, that's how it is.

If LinkedIn won't budge, unfortunately it's Waterfox that will have to.
Developers pretty please be so kind and see what can be done about it on Waterfox' side.

**Comment by hockeymikey** [comment]
The line it chokes on (syntax error) is 
`return{enabled:!!r&&this.lixes[r.lixKey]?.treatment!==t,lixedEngine:r?r.lixedEngine:e}}getLixedEngineMeta(e){return this.routingLix.engines[e]}}}))`
Looks to be optional chaining that we are missing: 
https://caniuse.com/mdn-javascript_operators_optional_chaining
Issue in question adding it:
https://bugzilla.mozilla.org/show_bug.cgi?id=1566143

Looks straight forward to implement.

**Comment by hockeymikey** [comment]
https://github.com/WaterfoxCo/Waterfox-Classic/issues/35

Is the issue that should be followed for a resolution. Looks like there is a backport from Seamonkey that may be of some help.

**Comment by rebop** [comment]
Thanks for that. Hopefully someone will pick up on it.

**Comment by rebop** [comment]
So, Linked In replies:

Hope this message finds you well.
Thank you for your patience. I apologize for the inconvenience caused.

I have heard back from our internal team and would like to inform you that, at the moment, Waterfox is not a supported browser and hence we are unable to test the issue. 
This is an instance where if Waterfox wishes to have support for LinkedIn on behalf of the users, the changes will need to happen on the Waterfox side as we do not test for or support Waterfox. 

Bob, I do understand your concern here and I wish there was something I could do to help you use LinkedIn smoothly on Waterfox but, this is how the platform is designed at the moment and we do not support this browser. For now, the only supported browsers are : Supported Internet Browsers for LinkedIn

Surprise, eh?

**Comment by hockeymikey** [comment]
Looks like this is fixed, I'm using 2022.06. Good to close?

**Comment by rebop** [comment]
It is working. Wish more was.

**Comment by hlloyge** [comment]
As rebop said.

Thank you developers, for the fix.
(Alas it took so long I meanwhile switched to another browser - well, not just because of this issue, though it was one one of deciding factors...)
